name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: IsaacJefferson7
          outputs: |
            ./github-contribution-grid-snake-dark.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
